import { SelectItem } from "@mantine/core";

export const Emociones = [
  { value: "Feliz", label: "Feliz" },
  { value: "Triste", label: "Triste" },
  { value: "Enojado", label: "Enojado" },
  { value: "Cansado", label: "Cansado" },
  { value: "Enamorado", label: "Enamorado" },
  { value: "Sorprendido", label: "Sorprendido" },
  { value: "Ansioso", label: "Ansioso" },
  { value: "Estresado", label: "Estresado" },
  { value: "Aburrido", label: "Aburrido" },
  { value: "Asustado", label: "Asustado" },
  { value: "Alegre", label: "Alegre" },
  { value: "Confundido", label: "Confundido" },
  { value: "Desanimado", label: "Desanimado" },
  { value: "Desesperado", label: "Desesperado" },
  { value: "Deprimido", label: "Deprimido" },
  { value: "Desilusionado", label: "Desilusionado" },
  { value: "Desmotivado", label: "Desmotivado" },
  { value: "Emocionado", label: "Emocionado" },
  { value: "Energico", label: "Energico" },
  { value: "Entusiasmado", label: "Entusiasmado" },
  { value: "Furioso", label: "Furioso" },
  { value: "Impaciente", label: "Impaciente" },
  { value: "Inspirado", label: "Inspirado" },
  { value: "Irritado", label: "Irritado" },
  { value: "Molesto", label: "Molesto" },
  { value: "Motivado", label: "Motivado" },
  { value: "Nervioso", label: "Nervioso" },
  { value: "Optimista", label: "Optimista" },
  { value: "Orgulloso", label: "Orgulloso" },
  { value: "Pensativo", label: "Pensativo" },
  { value: "Preocupado", label: "Preocupado" },
  { value: "Relajado", label: "Relajado" },
  { value: "Satisfecho", label: "Satisfecho" },
  { value: "Sereno", label: "Sereno" },
] as SelectItem[];
